[project]
name = 'Sustainable-Resource-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification]
path = 'contracts/certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.extraction-tracking]
path = 'contracts/extraction-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.reporting]
path = 'contracts/reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-verification]
path = 'contracts/resource-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
